### ISSUE TITLE
Separate nunit.engine.core.tests from nunit.engine.tests

### ISSUE THREAD

**Issue by CharliePoole** [nunit/nunit-console#1075]
The `nunit.engine` and `nunit.engine.core` assemblies are built for different sets of runtimes. The tests should match these rather than relying on conditional compilation to include the correct test assemblies.

Getting this done will make other work with nunit.engine.core much simpler.

**Comment by CharliePoole** [comment]
@mikkelbu Looks like this is almost ready! If so, I'll try to release tomorrow and include it. Is there anything I can do to help?

If we can't get it in, I'd like to address it right away in the next cycle. Having the tests combined is complicating several issues having to do with the engine and engine.core assemblies.

**Comment by mikkelbu** [comment]
I don't think I'll have time to work more it today (and I'm running out of battery in 15 minutes). If the CI passes then I think it is fine to include it in the release, but I'm also happy to release without it (if more changes are required) and then make it part of the next release.

Ps. I was hoping that I also could make `TestNet50EngineCore` run, but 3 tests are failing

```
Errors, Failures and Warnings

1) Failed : NUnit.Engine.Services.Tests.DriverServiceTests.CorrectDriverIsUsed("notest-assembly.dll",False,NUnit.Engine.Drivers.NUnitNetCore31Driver)
  Expected: instance of <NUnit.Engine.Drivers.NUnitNetCore31Driver>
  But was:  <NUnit.Engine.Drivers.InvalidAssemblyFrameworkDriver>
   at NUnit.Engine.Services.Tests.DriverServiceTests.CorrectDriverIsUsed(String fileName, Boolean skipNonTestAssemblies, Type expectedType) in C:\Temp\GitHub\WorkConsole\nunit-console\src\NUnitEngine\nunit.engine.core.tests\Services\DriverServiceTests.cs:line 56

2) Failed : NUnit.Engine.Services.Tests.DriverServiceTests.CorrectDriverIsUsed("nunit.engine.dll",True,NUnit.Engine.Drivers.SkippedAssemblyFrameworkDriver)
  Expected: instance of <NUnit.Engine.Drivers.SkippedAssemblyFrameworkDriver>
  But was:  <NUnit.Engine.Drivers.InvalidAssemblyFrameworkDriver>
   at NUnit.Engine.Services.Tests.DriverServiceTests.CorrectDriverIsUsed(String fileName, Boolean skipNonTestAssemblies, Type expectedType) in C:\Temp\GitHub\WorkConsole\nunit-console\src\NUnitEngine\nunit.engine.core.tests\Services\DriverServiceTests.cs:line 56

3) Failed : NUnit.Engine.Services.Tests.DriverServiceTests.CorrectDriverIsUsed("notest-assembly.dll",True,NUnit.Engine.Drivers.SkippedAssemblyFrameworkDriver)
  Expected: instance of <NUnit.Engine.Drivers.SkippedAssemblyFrameworkDriver>
  But was:  <NUnit.Engine.Drivers.InvalidAssemblyFrameworkDriver>
   at NUnit.Engine.Services.Tests.DriverServiceTests.CorrectDriverIsUsed(String fileName, Boolean skipNonTestAssemblies, Type expectedType) in C:\Temp\GitHub\WorkConsole\nunit-console\src\NUnitEngine\nunit.engine.core.tests\Services\DriverServiceTests.cs:line 56
```
