### ISSUE TITLE
NUnit.Engine 3.14.0 unable to explore .NET 5.0 test fixtures

### ISSUE THREAD

**Issue by bouchraRekhadda** [nunit/nunit-console#1159]
Hello,

We are using a custom NUnit test runner with `NUnit.Engine 3.14.0` to run our unit tests; in **.NET 5.0** the `Explore` throws a `ReflectionTypeLoadException` with this stack trace

>Inner exception: ReflectionTypeLoadException - Unable to load one or more of the requested types.
   **Could not load type 'System.IO.StringWriter' from assembly 'netstandard, Version=2.1.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'.
   Could not load type 'System.IO.StringWriter' from assembly 'netstandard, Version=2.1.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'.**
      at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
      at System.Reflection.RuntimeAssembly.get_DefinedTypes()
      at NUnit.Engine.Drivers.NUnitNetCore31Driver.CreateObject(String typeName, Object[] args)
      at NUnit.Engine.Drivers.NUnitNetCore31Driver.Load(String assemblyPath, IDictionary`2 settings)
      at NUnit.Engine.Runners.DirectTestRunner.LoadDriver(IFrameworkDriver driver, String testFile, TestPackage subPackage)
    - (no inner exception)
   There was an exception: NUnitEngineException - An exception occurred in the driver while loading tests.
      at NUnit.Engine.Runners.DirectTestRunner.LoadDriver(IFrameworkDriver driver, String testFile, TestPackage subPackage)
      at NUnit.Engine.Runners.DirectTestRunner.LoadPackage()
      at NUnit.Engine.Runners.DirectTestRunner.EnsurePackageIsLoaded()
      at NUnit.Engine.Runners.DirectTestRunner.Explore(TestFilter filter)
      at NUnit.Engine.Runners.MasterTestRunner.Explore(TestFilter filter)
      
 
The exception occurs for fewer of our test assemblies (all targeting .NET 5.0), and the `netstandard.dll` is indeed present in the output folder. 
I've also noticed the 3.14.0 is only compiled against `.NET Standard 2.0` & `.NET Core 3.1`, no `.NET 5.0` nor `.NET 6.0`. Would that explain the failure?
 
 I can manage to attach a sample reproduction if needed.
 Thanks for your help!
 
**PS**: my applogies if this was already mentioned in other issues, I didn't seem to find anything related to recent Engine **3.14.0** release

**Comment by bouchraRekhadda** [comment]
Our test runner is targeting both `.NET Core 3.1` and .NET Standard 2.0, so that explains the failure above; the fix would be to target `.NET 5.0` instead.
My sincere apologies for the false bug report, I'll close this issue.
