### ISSUE TITLE
'Could not load file or assembly 'nunit.framework, Version=3.13.3.0 or one of its dependencies.' running nunit3-console

### ISSUE THREAD

**Issue by albx** [nunit/nunit-console#1205]
Hi everyone,

We've just upgraded our test suite from NUnit v2 to the last NUnit3 version (3.13.3). Running those tests using Visual Studio (both 2022 and 2019) or Rider works fine, running those tests in our CI using the nunit3-console.exe will cause this error:

```
NUnit.Engine.NUnitEngineException : An exception occurred in the driver while loading tests.
  ----> System.IO.FileNotFoundException : Could not load file or assembly 'nunit.framework, Version=3.13.3.0, Culture=neutral, PublicKeyToken=2638cd05610744eb' or one of its dependencies. The system cannot find the file specified.

--NUnitEngineException
An exception occurred in the driver while loading tests.
   at NUnit.Engine.Runners.DirectTestRunner.LoadDriver(IFrameworkDriver driver, String testFile, TestPackage subPackage)
   at NUnit.Engine.Runners.DirectTestRunner.LoadPackage()
   at NUnit.Engine.Runners.DirectTestRunner.EnsurePackageIsLoaded()
   at NUnit.Engine.Runners.DirectTestRunner.RunTests(ITestEventListener listener, TestFilter filter)
   at NUnit.Engine.Runners.TestExecutionTask.Execute()
   at NUnit.Engine.Runners.AggregatingTestRunner.RunTestsSequentially(ITestEventListener listener, TestFilter filter, List`1 results, Boolean disposeRunners)
   at NUnit.Engine.Runners.AggregatingTestRunner.RunTests(ITestEventListener listener, TestFilter filter)
   at NUnit.Engine.Runners.MasterTestRunner.RunTests(ITestEventListener listener, TestFilter filter)
   at NUnit.Engine.Runners.MasterTestRunner.Run(ITestEventListener listener, TestFilter filter)
   at NUnit.ConsoleRunner.ConsoleRunner.RunTests(TestPackage package, TestFilter filter)
--
FileNotFoundException
Could not load file or assembly 'nunit.framework, Version=3.13.3.0, Culture=neutral, PublicKeyToken=2638cd05610744eb' or one of its dependencies. The system cannot find the file specified.
   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Activator.CreateInstance(String assemblyString, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, Evidence securityInfo, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(String assemblyName, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, Evidence securityInfo)
   at System.AppDomain.CreateInstance(String assemblyName, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, Evidence securityAttributes)
   at System.AppDomain.CreateInstanceAndUnwrap(String assemblyName, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, Evidence securityAttributes)
   at System.AppDomain.CreateInstanceAndUnwrap(String assemblyName, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, Evidence securityAttributes)
   at NUnit.Engine.Drivers.NUnit3FrameworkDriver.CreateObject(String typeName, Object[] args)
   at NUnit.Engine.Drivers.NUnit3FrameworkDriver.Load(String testAssemblyPath, IDictionary`2 settings)
   at NUnit.Engine.Runners.DirectTestRunner.LoadDriver(IFrameworkDriver driver, String testFile, TestPackage subPackage)
```
We're running the tests using a .nunit file with the command:
`nunit3-console.exe" .\PathToOurFolder\NunitServerTests.nunit --result:Test_nunit-result.xml;format=nunit2 `

Version of the nunit3-console in the CI is 3.15.0.
Same error trying running the console locally, using both 3.15.0 and 3.15.2 versions.
Locally I've downloaded the zip files and pointing to the net35 folder. Our projects are all based on .NET Framework 4.5.2.

Am I missing something?
Thanks to everyone for the help.

**Comment by albx** [comment]
Investigated a little bit more.
The problem isn't the console itself, since running the specific dll, all works fine.
We've a .nunit file build this way:

```
<NUnitProject>
  <Settings activeconfig="Debug" processModel="Single"/>
  <Config name="Debug">
    <assembly path="..\PathToAssembly1\bin\Debug\Assembly1.dll"/>
    <assembly path="..\PathToAssembly2\bin\Debug\Assembly2.dll"/>    
    <assembly path="..\PathToAssembly3\bin\Debug\Assembly3.dll" />
    <assembly path="..\PathToAssembly4\bin\Debug\Assembly4.dll" />
    <assembly path="..\PathToAssembly5\bin\Debug\Assembly5.dll" />
    <assembly path="..\PathToAssembly6\bin\Debug\Assembly6.dll" />
  </Config>
</NUnitProject>
``` 
All this projects target .NET Framework 4.5.2
Maybe some configuration that I'm missing?!

**Comment by albx** [comment]
Problem found.
I missed to specify the appbase on the `<Settings>` tag:
```
<NUnitProject>
  <Settings activeconfig="Debug" processModel="Single" appbase="..\"/>
  <Config name="Debug">
    <assembly path=".\PathToAssembly1\bin\Debug\Assembly1.dll"/>
    <assembly path=".\PathToAssembly2\bin\Debug\Assembly2.dll"/>    
    <assembly path=".\PathToAssembly3\bin\Debug\Assembly3.dll" />
    <assembly path=".\PathToAssembly4\bin\Debug\Assembly4.dll" />
    <assembly path=".\PathToAssembly5\bin\Debug\Assembly5.dll" />
    <assembly path=".\PathToAssembly6\bin\Debug\Assembly6.dll" />
  </Config>
</NUnitProject>
```
Pointing the appbase to the repository root solved the problem.
I'm closing this issue.
