### ISSUE TITLE
NUnit-console sporadically returns -100 error code

### ISSUE THREAD

**Issue by svg2003** [nunit/nunit-console#1262]
Hi,

We recently switched to nunit3.15 and see sporadically issues with nunit console, when it returns -100 error code.
With several hundreds projects it became a real issue. Below is the logs:

[InternalTrace.5176.Amat.Bridge.UserData.Test.dll.log](https://github.com/nunit/nunit-console/files/9945322/InternalTrace.5176.Amat.Bridge.UserData.Test.dll.log)
[InternalTrace.21736.log](https://github.com/nunit/nunit-console/files/9945323/InternalTrace.21736.log)
[nunit-agent_5176.log](https://github.com/nunit/nunit-console/files/9945324/nunit-agent_5176.log)
18:35:04.869   288>RunNUnit3AssemblyTests:
                     Run db tests from G:\Views\CGAFE\SR-680280\CGAFE\TmpRel\Bridge.Test\Amat.Bridge.UserData.Test.dll
                     G:\Views\CGAFE\SR-680280\CGAFE_tlbx_rel\ToolBox\tlbx\NUnit3.15\nunit3-console.exe --where="cat!=Debug and cat==CacheDb" --trace:Verbose --result:G:\Views\CGAFE\SR-680280\CGAFE\TmpRel\Bridge.Test\Amat.Bridge.UserData.Test.dll.DbTestResult.xml "G:\Views\CGAFE\SR-680280\CGAFE\TmpRel\Bridge.Test\Amat.Bridge.UserData.Test.dll"
                     NUnit Console 3.15.2 (Release)
                     Copyright (c) 2022 Charlie Poole, Rob Prouse
                     Saturday, November 5, 2022 6:35:05 PM
                     
                     Runtime Environment
                        OS Version: Microsoft Windows NT 6.2.9200.0
                        Runtime: .NET Framework CLR v4.0.30319.42000
                     
                     Test Files
                         G:\Views\CGAFE\SR-680280\CGAFE\TmpRel\Bridge.Test\Amat.Bridge.UserData.Test.dll
                     
                     Test Filters
                         Where: cat!=Debug and cat==CacheDb
                     
                     System.Net.Sockets.SocketException : An existing connection was forcibly closed by the remote host
                     
                     --SocketException
                     An existing connection was forcibly closed by the remote host
                     
                     Server stack trace: 
                        at System.Runtime.Remoting.Channels.SocketStream.Read(Byte[] buffer, Int32 offset, Int32 size)
                        at System.Runtime.Remoting.Channels.SocketHandler.ReadFromSocket(Byte[] buffer, Int32 offset, Int32 count)
                        at System.Runtime.Remoting.Channels.SocketHandler.Read(Byte[] buffer, Int32 offset, Int32 count)
                        at System.Runtime.Remoting.Channels.Tcp.TcpFixedLengthReadingStream.Read(Byte[] buffer, Int32 offset, Int32 count)
                        at System.IO.BinaryReader.ReadBytes(Int32 count)
                        at System.Runtime.Serialization.Formatters.Binary.SerializationHeaderRecord.Read(__BinaryParser input)
                        at System.Runtime.Serialization.Formatters.Binary.__BinaryParser.ReadSerializationHeaderRecord()
                        at System.Runtime.Serialization.Formatters.Binary.__BinaryParser.Run()
                        at System.Runtime.Serialization.Formatters.Binary.ObjectReader.Deserialize(HeaderHandler handler, __BinaryParser serParser, Boolean fCheck, Boolean isCrossAppDomain, IMethodCallMessage methodCallMessage)
                        at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Deserialize(Stream serializationStream, HeaderHandler handler, Boolean fCheck, Boolean isCrossAppDomain, IMethodCallMessage methodCallMessage)
                        at System.Runtime.Remoting.Channels.CoreChannel.DeserializeBinaryResponseMessage(Stream inputStream, IMethodCallMessage reqMsg, Boolean bStrictBinding)
                        at System.Runtime.Remoting.Channels.BinaryClientFormatterSink.SyncProcessMessage(IMessage msg)
                     
                     Exception rethrown at [0]: 
                        at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
                        at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
                        at NUnit.Engine.ITestAgent.Stop()
                        at NUnit.Engine.Runners.ProcessRunner.Dispose(Boolean disposing) in C:\Users\charlie\dev\NUnit\nunit-console\src\NUnitEngine\nunit.engine\Runners\ProcessRunner.cs:line 224
                        at NUnit.Engine.Runners.AbstractTestRunner.Dispose() in C:\Users\charlie\dev\NUnit\nunit-console\src\NUnitEngine\nunit.engine.core\Runners\AbstractTestRunner.cs:line 186
                        at NUnit.Engine.Runners.MasterTestRunner.Dispose(Boolean disposing) in C:\Users\charlie\dev\NUnit\nunit-console\src\NUnitEngine\nunit.engine\Runners\MasterTestRunner.cs:line 236
                        at NUnit.Engine.Runners.MasterTestRunner.Dispose() in C:\Users\charlie\dev\NUnit\nunit-console\src\NUnitEngine\nunit.engine\Runners\MasterTestRunner.cs:line 223
                        at NUnit.ConsoleRunner.ConsoleRunner.RunTests(TestPackage package, TestFilter filter) in C:\Users\charlie\dev\NUnit\nunit-console\src\NUnitConsole\nunit3-console\ConsoleRunner.cs:line 198
                        at NUnit.ConsoleRunner.Program.Main(String[] args) in C:\Users\charlie\dev\NUnit\nunit-console\src\NUnitConsole\nunit3-console\Program.cs:line 114
                     
18:35:06.976   288>G:\Views\CGAFE\SR-680280\CGAFE\Products\CgaFE.Build.Test.proj(61,5): error MSB3073: The command "G:\Views\CGAFE\SR-680280\CGAFE_tlbx_rel\ToolBox\tlbx\NUnit3.15\nunit3-console.exe --where="cat!=Debug and cat==CacheDb" --trace:Verbose --result:G:\Views\CGAFE\SR-680280\CGAFE\TmpRel\Bridge.Test\Amat.Bridge.UserData.Test.dll.DbTestResult.xml "G:\Views\CGAFE\SR-680280\CGAFE\TmpRel\Bridge.Test\Amat.Bridge.UserData.Test.dll"" exited with code -100.

**Comment by CharliePoole** [comment]
Over 24 months without further discussion. Refers to 3.15, which is not recommended for use.
