### ISSUE TITLE
Trying to run tests in main using Rider gives MissingMethodException

### ISSUE THREAD

**Issue by lahma** [nunit/nunit-console#1342]
* latest main
* change project `nunit.engine.tests` to be a class library, install `Microsoft.NET.Test.Sdk`, remove `Program.cs`
* try to run tests using Rider

```text
Message = “
  Method not found: 'Void NUnit.Engine.TestPackage..ctor(System.String)'., reason: System.MissingMethodException: Method not found: 'Void NUnit.Engine.TestPackage..ctor(System.String)'.
     at JetBrains.ReSharper.TestRunner.Adapters.NUnit3.NUnitRunner.CreateTestPackage(NUnitTestAssemblyTask assemblyTask, IAdapterSettings settings, TestRunRequest runRequest, RemoteTaskDepot depot)
     at JetBrains.ReSharper.TestRunner.Adapters.NUnit3.NUnitRunner.<>c__DisplayClass5_0.<RunTests>b__0(NUnitTestAssemblyTask assemblyTask) in Z:\BuildAgent\work\1b668fe37ef92293\ReSharperTestRunner\src\Adapters\TestRunner.Adapters.NUnit3\NUnitRunner.cs:line 61
     at JetBrains.ReSharper.TestRunner.Adapters.NUnit3.NUnitRunner.WithContainerAsNUnitAssembly(TestContainer container, Action`1 action) in Z:\BuildAgent\work\1b668fe37ef92293\ReSharperTestRunner\src\Adapters\TestRunner.Adapters.NUnit3\NUnitRunner.cs:line 133
     at JetBrains.ReSharper.TestRunner.Adapters.NUnit3.NUnitRunner.RunTests(TestRunRequest request, ITestDiscoverySink discoverySink, ITestExecutionSink executionSink) in Z:\BuildAgent\work\1b668fe37ef92293\ReSharperTestRunner\src\Adapters\TestRunner.Adapters.NUnit3\NUnitRunner.cs:line 85
     at JetBrains.ReSharper.TestRunner.Implementation.UnitTestRemoteAgent.Execute(TestRunRequest request)
     at JetBrains.ReSharper.TestRunner.Implementation.ClientEndpoint.<>c__DisplayClass4_1.<TryRegisterHandler>b__1()
     at System.Threading.Tasks.Task`1.InnerInvoke()
     at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)
     at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
  --- End of stack trace from previous location where exception was thrown ---
     at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
     at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
  --- End of stack trace from previous location where exception was thrown ---
     at JetBrains.ReSharper.TestRunner.Implementation.ClientEndpoint.RunAndLog(Func`2 handler, IAutoRegisterInProtocol message)
```

I think the cause for this is [this commit](https://github.com/nunit/nunit-console/commit/b9cd4ecaa0200e70d7804db104babcaa693bf09f) which took away the constructor taking single string as parameter that Rider is expecting to provide.

**Comment by CharliePoole** [comment]
A few years ago, a decision was made to convert the tests to run under NUnitLite so that the engine would not, through its tests, be in some way dependent on the console runner. The change you describe would disable NUnitLite as a runner. It's hard to see why you would want to do that as a general change to the tests.

As far as generally supporting Rider running NUnit tests, the main branch is aimed at version 4.0, which contains a great many breaking changes. Usually, a third-party runner will fix their code to work with the new major release __after__ that release rather than before it. :-)

You don't say what constructor changed, but I'm guessing you mean TestPackage. There is extensive discussion in the issues about why that was changed for 4.0. The completely different behavior of the single constructor from the array constructor is a fault in NUnit 3, which we felt we could not fix without breaking many users. For 4.0 we eliminated that constructor, simplifying the implementation of a large number of crucial classes which depend on it.

Of course, if you didn't intend to be making a change for version 4.0, then you can simply stop working from main, The version3 branch is a long-running branch for version3 releases, created at the same time that main switched over to version 4 development.

**Comment by lahma** [comment]
Thank you for the background information. I was just thinking whether adding the expected constructor back keeping the new ones would have been enough, but as you've described one can expect that IDE maintainers will adjust on their side so no change is probably needed. I was just hoping to run the tests in IDE instead of using the command line runner.

**Comment by OsirisTerje** [comment]
Rider has their own internal Nunit.engine-look-alike, based off 3.11 iirc.

**Comment by CharliePoole** [comment]
Didn't know that. Of course, they're allowed to do that by the license terms and that was a decision we made knowingly. But then they will have to keep maintaining that themselves.

Of course, I did the same thing when I made the TestCentric engine. :-)
