### ISSUE TITLE
Occasionally getting No connection could be made because the target machine actively refused it

### ISSUE THREAD

**Issue by varnk** [nunit/nunit-console#1348]
This problem is intermittent.  Sometimes when I run NUnit tests, the test run terminates with the following exception:

```
18:37:29  --SocketException
18:37:29  No connection could be made because the target machine actively refused it 127.0.0.1:12723
18:37:29  
18:37:29  Server stack trace: 
18:37:29     at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
18:37:29     at System.Net.Sockets.Socket.Connect(EndPoint remoteEP)
18:37:29     at System.Runtime.Remoting.Channels.RemoteConnection.CreateNewSocket(EndPoint ipEndPoint)
18:37:29     at System.Runtime.Remoting.Channels.RemoteConnection.CreateNewSocket()
18:37:29     at System.Runtime.Remoting.Channels.RemoteConnection.GetSocket()
18:37:29     at System.Runtime.Remoting.Channels.SocketCache.GetSocket(String machinePortAndSid, Boolean openNew)
18:37:29     at System.Runtime.Remoting.Channels.Tcp.TcpClientTransportSink.SendRequestWithRetry(IMessage msg, ITransportHeaders requestHeaders, Stream requestStream)
18:37:29     at System.Runtime.Remoting.Channels.Tcp.TcpClientTransportSink.ProcessMessage(IMessage msg, ITransportHeaders requestHeaders, Stream requestStream, ITransportHeaders& responseHeaders, Stream& responseStream)
18:37:29     at System.Runtime.Remoting.Channels.BinaryClientFormatterSink.SyncProcessMessage(IMessage msg)
18:37:29  
18:37:29  Exception rethrown at [0]: 
18:37:29     at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
18:37:29     at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
18:37:29     at NUnit.Engine.ITestAgent.Stop()
18:37:29     at NUnit.Engine.Communication.Transports.Remoting.TestAgentRemotingProxy.Stop()
18:37:29     at NUnit.Engine.Runners.ProcessRunner.Dispose(Boolean disposing)
18:37:29     at NUnit.Engine.Runners.AbstractTestRunner.Dispose()
18:37:29     at NUnit.Engine.Runners.MasterTestRunner.Dispose(Boolean disposing)
18:37:29     at NUnit.Engine.Runners.MasterTestRunner.Dispose()
18:37:29     at NUnit.ConsoleRunner.ConsoleRunner.RunTests(TestPackage package, TestFilter filter)
18:37:29     at NUnit.ConsoleRunner.ConsoleRunner.Execute()
18:37:29     at NUnit.ConsoleRunner.Program.Main(String[] args)
18:37:29  
[Pipeline] echo
18:37:29  NUnit Status Result Code = -100
```

Also found this Application Event in Windows EventViewer about 10 minutes before the above exception was reported (not sure if it is related or not):
```
Log Name:      Application
Source:        Windows Error Reporting
Date:          6/21/2023 6:21:25 PM
Event ID:      1001
Task Category: None
Level:         Information
Keywords:      Classic
User:          N/A
Computer:      xxxxxxxxxxxxxxxxxxxxx
Description:
Fault bucket , type 0
Event Name: BEX
Response: Not available
Cab Id: 0

Problem signature:
P1: nunit-agent-x86.exe
P2: 3.16.3.0
P3: 8f6e336e
P4: StackHash_0a9e
P5: 0.0.0.0
P6: 00000000
P7: 7e3a3a79
P8: c0000005
P9: 00000008
P10: 

Attached files:
C:\Windows\Temp\WERBE60.tmp.appcompat.txt
C:\Windows\Temp\WERBEFD.tmp.WERInternalMetadata.xml
C:\Windows\Temp\WERBF1D.tmp.hdmp
C:\Windows\Temp\WEREF13.tmp.mdmp

These files may be available here:
C:\ProgramData\Microsoft\Windows\WER\ReportQueue\AppCrash_nunit-agent-x86._acf762464aa69955f7e65dc83f8a48af12e3b10_cab_129ff27a

Analysis symbol: 
Rechecking for solution: 0
Report Id: e64b207d-1081-11ee-9cfd-00270e375c17
Report Status: 0
Hashed bucket: %22
Cab Guid: %23
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Windows Error Reporting" />
    <EventID Qualifiers="0">1001</EventID>
    <Level>4</Level>
    <Task>0</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2023-06-21T22:21:25.0000000Z" />
    <EventRecordID>11580847</EventRecordID>
    <Channel>Application</Channel>
    <Computer>xxxxxxxxxxxxx</Computer>
    <Security />
  </System>
  <EventData>
    <Data>
    </Data>
    <Data>0</Data>
    <Data>BEX</Data>
    <Data>Not available</Data>
    <Data>0</Data>
    <Data>nunit-agent-x86.exe</Data>
    <Data>3.16.3.0</Data>
    <Data>8f6e336e</Data>
    <Data>StackHash_0a9e</Data>
    <Data>0.0.0.0</Data>
    <Data>00000000</Data>
    <Data>7e3a3a79</Data>
    <Data>c0000005</Data>
    <Data>00000008</Data>
    <Data>
    </Data>
    <Data>
C:\Windows\Temp\WERBE60.tmp.appcompat.txt
C:\Windows\Temp\WERBEFD.tmp.WERInternalMetadata.xml
C:\Windows\Temp\WERBF1D.tmp.hdmp
C:\Windows\Temp\WEREF13.tmp.mdmp</Data>
    <Data>C:\ProgramData\Microsoft\Windows\WER\ReportQueue\AppCrash_nunit-agent-x86._acf762464aa69955f7e65dc83f8a48af12e3b10_cab_129ff27a</Data>
    <Data>
    </Data>
    <Data>0</Data>
    <Data>e64b207d-1081-11ee-9cfd-00270e375c17</Data>
    <Data>0</Data>
  </EventData>
</Event>
```

### Requested Info
Command line being used: --x86 --work=.\TestOutput --timeout=1800000 --trace=Off --result="TestResult.xml"
Method of installation: NuGet
Log files: unavailable at the moment
Version of the NUnit Engine/Console: version 3.16.3
Versions of the NUnit Framework in use: 3.13.3
I cannot use --inprocess flag due to incompatibility with --x86

NUnit-Console is launched via Jenkins job.

**Comment by varnk** [comment]
This issue may have been the result of a bug in one of the dependent DLLs that my test DLL used.  I have since updated the DLL and it seems to be working now.  However, I would like to point out that I have seen this issue on occasion before this bug was introduced, so I am not sure if it should be closed or not.

**Comment by OsirisTerje** [comment]
We do have several of these, the problem being having a good repro.
https://github.com/nunit/nunit-console/issues?q=is%3Aissue+target+machine+actively+refused

So closing for now
