### ISSUE TITLE
Assert.Multiple test failure stack traces

### ISSUE THREAD

**Issue by ScottWrightWTG** [nunit/nunit-console#1385]
Hi Engine Team,

We are updating to the latest NUnit3TestAdapter (4.5.0) and NUnit.Engine (3.15.4) combination. 
We are testing failures within an Assert.Multiple at multiple levels, [Test], [TearDown] and [OneTimeTearDown]. Previously each assertion test failure would return a stack trace. In the current version the first failure in each Assert.Multiple failure returns a stack trace. Is this a new expected behavior?

```
<failure>
  <message>
    <![CDATA[Multiple failures or warnings in test:
  1)   Expected: True
  But was:  False

  2)   Expected: False
  But was:  True


TearDown : NUnit.Framework.MultipleAssertException : Multiple failures or warnings in test:
  1)   Expected: True
  But was:  False

  2)   Expected: False
  But was:  True

]]>
  </message>
  <stack-trace>
    <![CDATA[--TearDown
   at NUnit.Framework.Assert.Multiple(TestDelegate testDelegate)]]>
  </stack-trace>
</failure>
<assertions>
  <assertion result="Failed">
    <message>
      <![CDATA[  Expected: True
  But was:  False
]]>
    </message>
    <stack-trace>
      <![CDATA[   at MyTests.MyTestFixture.<BlowUpOnce>b__4()
   at NUnit.Framework.Assert.Multiple(TestDelegate testDelegate)
]]>
    </stack-trace>
  </assertion>
  <assertion result="Failed">
    <message>
      <![CDATA[  Expected: False
  But was:  True
]]>
    </message>
    <stack-trace><![CDATA[]]></stack-trace>
  </assertion>
</assertions>
<test-case id="1-1001" name="BlowUp" fullname="MyTests.MyTestFixture.BlowUp" methodname="BlowUp" classname="MyTests.MyTestFixture" runstate="Runnable" seed="686156416" result="Failed" label="Error" start-time="2024-01-18T01:33:52.4606672Z" end-time="2024-01-18T01:33:52.5506776Z" duration="0.089821" asserts="4">
  <failure>
    <message>
      <![CDATA[Multiple failures or warnings in test:
  1)   Expected: True
  But was:  False

  2)   Expected: False
  But was:  True

  3)   Expected: True
  But was:  False

  4)   Expected: False
  But was:  True


TearDown : NUnit.Framework.MultipleAssertException : Multiple failures or warnings in test:
  1)   Expected: True
  But was:  False

  2)   Expected: False
  But was:  True

  3)   Expected: True
  But was:  False

  4)   Expected: False
  But was:  True

]]>
    </message>
    <stack-trace>
      <![CDATA[--TearDown
   at NUnit.Framework.Assert.Multiple(TestDelegate testDelegate)]]>
    </stack-trace>
  </failure>
  <assertions>
    <assertion result="Failed">
      <message>
        <![CDATA[  Expected: True
  But was:  False
]]>
      </message>
      <stack-trace>
        <![CDATA[   at MyTests.MyTestFixture.<BlowUp>b__0()
   at NUnit.Framework.Assert.Multiple(TestDelegate testDelegate)
]]>
      </stack-trace>
    </assertion>
    <assertion result="Failed">
      <message>
        <![CDATA[  Expected: False
  But was:  True
]]>
      </message>
      <stack-trace><![CDATA[]]></stack-trace>
    </assertion>
    <assertion result="Failed">
      <message>
        <![CDATA[  Expected: True
  But was:  False
]]>
      </message>
      <stack-trace>
        <![CDATA[   at MyTests.MyTestFixture.<BlowUpEach>b__2()
   at NUnit.Framework.Assert.Multiple(TestDelegate testDelegate)
]]>
      </stack-trace>
    </assertion>
    <assertion result="Failed">
      <message>
        <![CDATA[  Expected: False
  But was:  True
]]>
      </message>
      <stack-trace><![CDATA[]]></stack-trace>
    </assertion>
  </assertions>
</test-case>
```

**Comment by OsirisTerje** [comment]
1. Are you using the console or dotnet ?

2. Can you please upload a repro project?

You can a) Add it as a PR to https://github.com/nunit/nunit3-vs-adapter.issues, add it as a separate folder named IssueXXX where the XXX is the issue number, or b) Add it as a zipped attachment here , or c) Add it to your own repo and just post the link. 

Make it as small as you can, it should compile "as is".

3. Where do you see the output shown above?   from the adapter dump files or from the console?

4.  

>  Previously each assertion test failure would return a stack trace

Which version do you refer to here?

**Comment by ScottWrightWTG** [comment]
Sorry my bad,

Have been investigating and found that we were compiling our test code without the debug information (pdb). Enabled this and the stack trace is showing for everything.

Regards Scott
