### ISSUE TITLE
nunit3-console doesn't see nugets from Microsoft.AspNetCore.App

### ISSUE THREAD

**Issue by Harmyder** [nunit/nunit-console#1392]
I have the following project and test

``` xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.6.0" />
    <PackageReference Include="NUnit" Version="3.13.3" />
    <PackageReference Include="NUnit3TestAdapter" Version="4.2.1" />
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
  
</Project>
```

``` csharp
[Test]
public void Test1()
{
    Assembly.Load("Microsoft.AspNetCore, Version=8.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60");
}
```

I can run fine this project from Visual Studio but then I run it from command line with `nunit3-console nunittests.dll` I see the following error

> System.IO.FileNotFoundException : Could not load file or assembly 'Microsoft.AspNetCore, Version=8.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified.
>    at System.Reflection.RuntimeAssembly.InternalLoad(AssemblyName assemblyName, StackCrawlMark& stackMark, AssemblyLoadContext assemblyLoadContext, RuntimeAssembly requestingAssembly, Boolean throwOnFileNotFound)
>    at System.Reflection.Assembly.Load(String assemblyString)
>    at NUnitTests.Tests.Test1() in D:\Yola\Test22\NUnitTests\UnitTest1.cs:line 16
>    at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
>    at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)

If I use `Assembly.LoadFrom` with the full path it is able to load the DLL.

**Comment by CharliePoole** [comment]
@Harmyder I added your load test to our existing package (integration) test for AspNETCore. All tests continue to pass in main. Can you try the same test using the latest dev build from our MyGet feed?

**Comment by CharliePoole** [comment]
@bthharper Your comment is a bit general and may call for a separate issue with more specific info. However, I'd suggest you also try the latest build on MyGet to see if it works.

I agree that modifying the runtime config for the console or agents is not satisfactory. It's also not possible for us to do it, since that would mean that nobody could use the console runner unless they had all those frameworks referenced installed, which is not always the case in certain test situations.

BTW, since you fixed your problem by changing the runtime config for the console itself, I deduce that you are using the .NET Core version of the runner rather than the standard runner. If you file an issue, please be sure  to specify that to avoid confusion. I'm afraid you can't rely on me to remember it, as I'm pretty much stateless when working bugs. :-)

**Comment by bthharper** [comment]
@CharliePoole - thanks for replying, I can raise a separate issue if that would help.  

To clarify, I unit testing .NET 8 (so .NET Core) assemblies against `nunit.console\net8.0\nunit3-console.exe`.

I will try the latest build and see if that helps.

**Comment by CharliePoole** [comment]
@Harmyder 
Are you also using the net8.0 build of nunit3-console.exe? That's important since the .net 8.0 build has significant functional differences from the standard runner.
