### ISSUE TITLE
SocketException when running nunit console involving .Net 8.0 DLLs

### ISSUE THREAD

**Issue by WindingWinter** [nunit/nunit-console#1470]
This is probably a wild goose chase but anyway, let me just put it here and see where it leads us.

When I run my nunit console tests ( 3.18.1 version), involving .net 8.0 DLLs, I got the dread ` --SocketException` exception. When I turn on the trace to `Verbose`, this is the best and most useful information I can glean from the log file. 

```
18:19:45.722 Error [ 1] ProcessRunner: Failed to run remote tests --SocketException
An existing connection was forcibly closed by the remote host
   at NUnit.Engine.Communication.Transports.Tcp.SocketReader.GetNextMessage()
   at NUnit.Engine.Communication.Transports.Tcp.TestAgentTcpProxy.TestRunResult(ITestEventListener listener)
   at NUnit.Engine.Runners.ProcessRunner.RunTests(ITestEventListener listener, TestFilter filter)

18:19:45.723 Info  [ 1] ProcessRunner: Unloading MiTS.IntegrationTest.dll
18:19:45.724 Warning [ 1] ProcessRunner: Failed to unload the remote runner. --SocketException
An existing connection was forcibly closed by the remote host
   at NUnit.Engine.Communication.Transports.Tcp.TestAgentTcpProxy.SendCommandMessage(String command, Object[] arguments)
   at NUnit.Engine.Runners.ProcessRunner.UnloadPackage()

18:19:45.724 Error [ 1] ProcessRunner: System.Net.Sockets.SocketException : An existing connection was forcibly closed by the remote host
18:19:45.724 Error [ 1] ProcessRunner: --SocketException
An existing connection was forcibly closed by the remote host
   at NUnit.Engine.Communication.Transports.Tcp.TestAgentTcpProxy.SendCommandMessage(String command, Object[] arguments)
   at NUnit.Engine.Runners.ProcessRunner.UnloadPackage()
   at NUnit.Engine.Runners.ProcessRunner.Dispose(Boolean disposing)

```

Any idea how I can debug further, without actually trying to scale down the whole thing and reproduce it in a small sample? This is my last resort which I hope I don't have to go through.

**Comment by WindingWinter** [comment]
Oh, I've managed to get the exact stack trace! Let me close this one

**Comment by OsirisTerje** [comment]
?
