### ISSUE TITLE
Execution failed with message: Object reference not set to an instance of an object. 

### ISSUE THREAD

**Issue by Droni** [nunit/nunit-console#180]
nunit-console/src/NUnitEngine/nunit.engine/Services/TestAgency.cs 

 Object reference not set to an instance of an object. 
    at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at NUnit.Engine.Services.TestAgency.LaunchAgentProcess(TestPackage package)
   at NUnit.Engine.Services.TestAgency.CreateRemoteAgent(TestPackage package, Int32 waitTime)
   at NUnit.Engine.Runners.ProcessRunner.CreateAgentAndRunner()

I have found that it is possible on multi-thread execution and this problem is fixed when I have added the lock for the _agentData field on all occurrences.

**Comment by CharliePoole** [comment]
This matches our conclusions on #168, which the present issue duplicates.
