### ISSUE TITLE
NetStandard Null ReferenceExcpetion

### ISSUE THREAD

**Issue by przemo098** [nunit/nunit-console#277]
Hello

I tried to run Nunit3 console at your test project 

> nunit-console\src\NUnitEngine\nunit.engine.tests.netstandard\nunit.engine.tests.netstandard.csproj

But I got this outPut:
```
PS C:\Repos\core-net-api\packages\NUnit.ConsoleRunner.3.7.0\tools> .\nunit3-console.exe "C:\Repos\nunit-console\src\NUnitEngine\nunit.engine.tests.netstandard\nunit.engine.tests.netstandard.csproj"
NUnit Console Runner 3.7.0
Copyright (c) 2017 Charlie Poole, Rob Prouse

Runtime Environment
   OS Version: Microsoft Windows NT 10.0.15063.0
  CLR Version: 4.0.30319.42000

Test Files
    C:\Repos\nunit-console\src\NUnitEngine\nunit.engine.tests.netstandard\nunit.engine.tests.netstandard.csproj

System.ArgumentException: Invalid project file format: nunit.engine.tests.netstandard.csproj ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at NUnit.Engine.Services.ProjectLoaders.VSProject.LoadMSBuildProject()
   at NUnit.Engine.Services.ProjectLoaders.VSProject.Load()
   --- End of inner exception stack trace ---
   at NUnit.Engine.Services.ProjectLoaders.VSProject.ThrowInvalidFormat(String projectPath, Exception e)
   at NUnit.Engine.Services.ProjectLoaders.VSProject.Load()
   at NUnit.Engine.Services.ProjectLoaders.VisualStudioProjectLoader.LoadFrom(String path)
   at NUnit.Engine.Services.ProjectService.ExpandProjectPackage(TestPackage package)
   at NUnit.Engine.Runners.MasterTestRunner.ExpandProjects(TestPackage package)
   at NUnit.Engine.Runners.MasterTestRunner.EnsurePackagesAreExpanded(TestPackage package)
   at NUnit.Engine.Runners.MasterTestRunner.EnsurePackagesAreExpanded(TestPackage package)
   at NUnit.Engine.Runners.MasterTestRunner.InitializePackage()
   at NUnit.Engine.TestEngine.GetRunner(TestPackage package)
   at NUnit.ConsoleRunner.ConsoleRunner.RunTests(TestPackage package, TestFilter filter)
   at NUnit.ConsoleRunner.Program.Main(String[] args)
PS C:\Repos\core-net-api\packages\NUnit.ConsoleRunner.3.7.0\tools>
```

I got clean installation with Visual Studio 2017.
Issue started with adapter which were not working... (but Resharper can run tests...)
So I used your nunit3-console. It's working for any project (normal .Net framework) but not for NetStandard or .Net core.
Maybe I'm doing something wrong...
I got Nunit3 package / console and nunit3 adapter.
But for project from nunit-console\src\NUnitEngine\nunit.engine.tests I got following outPut with errors :)

```
PS C:\Repos\core-net-api\packages\NUnit.ConsoleRunner.3.7.0\tools> .\nunit3-console.exe "C:\Repos\nunit-console\src\NUnitEngine\nunit.engine.tests\nunit.engine.tests.csproj"
NUnit Console Runner 3.7.0
Copyright (c) 2017 Charlie Poole, Rob Prouse

Runtime Environment
   OS Version: Microsoft Windows NT 10.0.15063.0
  CLR Version: 4.0.30319.42000

Test Files
    C:\Repos\nunit-console\src\NUnitEngine\nunit.engine.tests\nunit.engine.tests.csproj

=> NUnit.Engine.Services.Tests.RuntimeFrameworkServiceTests.AvailableFrameworks
Available: .NET 2.0
Available: .NET 3.0
Available: .NET 3.5
Available: .NET 4.0
Available: .NET 4.5
=> NUnit.Engine.Tests.RuntimeFrameworkTests.AvailableFrameworksList
Available: .NET 2.0
Available: .NET 3.0
Available: .NET 3.5
Available: .NET 4.0
Available: .NET 4.5
=> NUnit.Engine.Tests.RuntimeFrameworkTests.CurrentFrameworkMustBeAvailable
Current framework is .NET 4.5 (net-4.5)

Tests Not Run

1) Explicit : NUnit.Engine.Tests.HangingAppDomainFixture.PassingTest
OneTimeSetUp:

Errors, Failures and Warnings

1) Failed : NUnit.Engine.Runners.Tests.MasterTestRunnerTests.CountTestCases
  Expected: 31
  But was:  0
at NUnit.Engine.Runners.Tests.MasterTestRunnerTests.CountTestCases() in C:\Repos\nunit-console\src\NUnitEngine\nunit.engine.tests\Runners\MasterTestRunnerTests.cs:line 94

2) Failed : NUnit.Engine.Runners.Tests.MasterTestRunnerTests.Explore
  Expected: 31
  But was:  0
at NUnit.Engine.Runners.Tests.MasterTestRunnerTests.Explore() in C:\Repos\nunit-console\src\NUnitEngine\nunit.engine.tests\Runners\MasterTestRunnerTests.cs:line 103

3) Failed : NUnit.Engine.Runners.Tests.MasterTestRunnerTests.Load
  Expected: 31
  But was:  0
at NUnit.Engine.Runners.Tests.MasterTestRunnerTests.Load() in C:\Repos\nunit-console\src\NUnitEngine\nunit.engine.tests\Runners\MasterTestRunnerTests.cs:line 86

4) Failed : NUnit.Engine.Runners.Tests.MasterTestRunnerTests.Run
  Expected: 31
  But was:  0
at NUnit.Engine.Runners.Tests.MasterTestRunnerTests.CheckTestRunResult(XmlNode result) in C:\Repos\nunit-console\src\NUnitEngine\nunit.engine.tests\Runners\MasterTestRunnerTests.cs:line 133
at NUnit.Engine.Runners.Tests.MasterTestRunnerTests.Run() in C:\Repos\nunit-console\src\NUnitEngine\nunit.engine.tests\Runners\MasterTestRunnerTests.cs:line 116

5) Failed : NUnit.Engine.Runners.Tests.MasterTestRunnerTests.RunAsync
  Expected: 31
  But was:  0
at NUnit.Engine.Runners.Tests.MasterTestRunnerTests.CheckTestRunResult(XmlNode result) in C:\Repos\nunit-console\src\NUnitEngine\nunit.engine.tests\Runners\MasterTestRunnerTests.cs:line 133
at NUnit.Engine.Runners.Tests.MasterTestRunnerTests.RunAsync() in C:\Repos\nunit-console\src\NUnitEngine\nunit.engine.tests\Runners\MasterTestRunnerTests.cs:line 126

6) Failed : NUnit.Engine.Runners.Tests.TestEngineRunnerTests<LocalTestRunner>.CountTestCases
  Expected: 31
  But was:  0
at NUnit.Engine.Runners.Tests.TestEngineRunnerTests`1.CountTestCases() in C:\Repos\nunit-console\src\NUnitEngine\nunit.engine.tests\Runners\TestEngineRunnerTests.cs:line 103

7) Failed : NUnit.Engine.Runners.Tests.TestEngineRunnerTests<LocalTestRunner>.Explore
  Expected: 31
  But was:  0
at NUnit.Engine.Runners.Tests.TestEngineRunnerTests`1.CheckBasicResult(XmlNode node) in C:\Repos\nunit-console\src\NUnitEngine\nunit.engine.tests\Runners\TestEngineRunnerTests.cs:line 157
at NUnit.Engine.Runners.Tests.TestEngineRunnerTests`1.CheckBasicResult(TestEngineResult result) in C:\Repos\nunit-console\src\NUnitEngine\nunit.engine.tests\Runners\TestEngineRunnerTests.cs:li
at NUnit.Engine.Runners.Tests.TestEngineRunnerTests`1.Explore() in C:\Repos\nunit-console\src\NUnitEngine\nunit.engine.tests\Runners\TestEngineRunnerTests.cs:line 111

8) Failed : NUnit.Engine.Runners.Tests.TestEngineRunnerTests<LocalTestRunner>.Load
  Expected: 31
  But was:  0
at NUnit.Engine.Runners.Tests.TestEngineRunnerTests`1.CheckBasicResult(XmlNode node) in C:\Repos\nunit-console\src\NUnitEngine\nunit.engine.tests\Runners\TestEngineRunnerTests.cs:line 157
at NUnit.Engine.Runners.Tests.TestEngineRunnerTests`1.CheckBasicResult(TestEngineResult result) in C:\Repos\nunit-console\src\NUnitEngine\nunit.engine.tests\Runners\TestEngineRunnerTests.cs:li
at NUnit.Engine.Runners.Tests.TestEngineRunnerTests`1.Load() in C:\Repos\nunit-console\src\NUnitEngine\nunit.engine.tests\Runners\TestEngineRunnerTests.cs:line 96

9) Failed : NUnit.Engine.Runners.Tests.TestEngineRunnerTests<LocalTestRunner>.Run
  Expected: 31
  But was:  0
at NUnit.Engine.Runners.Tests.TestEngineRunnerTests`1.CheckBasicResult(XmlNode node) in C:\Repos\nunit-console\src\NUnitEngine\nunit.engine.tests\Runners\TestEngineRunnerTests.cs:line 157
at NUnit.Engine.Runners.Tests.TestEngineRunnerTests`1.CheckRunResult(XmlNode result) in C:\Repos\nunit-console\src\NUnitEngine\nunit.engine.tests\Runners\TestEngineRunnerTests.cs:line 169
at NUnit.Engine.Runners.Tests.TestEngineRunnerTests`1.CheckRunResult(TestEngineResult result) in C:\Repos\nunit-console\src\NUnitEngine\nunit.engine.tests\Runners\TestEngineRunnerTests.cs:line
at NUnit.Engine.Runners.Tests.TestEngineRunnerTests`1.Run() in C:\Repos\nunit-console\src\NUnitEngine\nunit.engine.tests\Runners\TestEngineRunnerTests.cs:line 119

10) Failed : NUnit.Engine.Runners.Tests.TestEngineRunnerTests<LocalTestRunner>.RunAsync
  Expected: 31
  But was:  0
at NUnit.Engine.Runners.Tests.TestEngineRunnerTests`1.CheckBasicResult(XmlNode node) in C:\Repos\nunit-console\src\NUnitEngine\nunit.engine.tests\Runners\TestEngineRunnerTests.cs:line 157
at NUnit.Engine.Runners.Tests.TestEngineRunnerTests`1.CheckRunResult(XmlNode result) in C:\Repos\nunit-console\src\NUnitEngine\nunit.engine.tests\Runners\TestEngineRunnerTests.cs:line 169
at NUnit.Engine.Runners.Tests.TestEngineRunnerTests`1.CheckRunResult(TestEngineResult result) in C:\Repos\nunit-console\src\NUnitEngine\nunit.engine.tests\Runners\TestEngineRunnerTests.cs:line
at NUnit.Engine.Runners.Tests.TestEngineRunnerTests`1.RunAsync() in C:\Repos\nunit-console\src\NUnitEngine\nunit.engine.tests\Runners\TestEngineRunnerTests.cs:line 133

11) Failed : NUnit.Engine.Runners.Tests.TestEngineRunnerTests<MultipleTestDomainRunner>(1).CountTestCases
  Expected: 31
  But was:  0
at NUnit.Engine.Runners.Tests.TestEngineRunnerTests`1.CountTestCases() in C:\Repos\nunit-console\src\NUnitEngine\nunit.engine.tests\Runners\TestEngineRunnerTests.cs:line 103

12) Failed : NUnit.Engine.Runners.Tests.TestEngineRunnerTests<MultipleTestDomainRunner>(1).Explore
  Expected: 31
  But was:  0
at NUnit.Engine.Runners.Tests.TestEngineRunnerTests`1.CheckBasicResult(XmlNode node) in C:\Repos\nunit-console\src\NUnitEngine\nunit.engine.tests\Runners\TestEngineRunnerTests.cs:line 157
at NUnit.Engine.Runners.Tests.TestEngineRunnerTests`1.CheckBasicResult(TestEngineResult result) in C:\Repos\nunit-console\src\NUnitEngine\nunit.engine.tests\Runners\TestEngineRunnerTests.cs:li
at NUnit.Engine.Runners.Tests.TestEngineRunnerTests`1.Explore() in C:\Repos\nunit-console\src\NUnitEngine\nunit.engine.tests\Runners\TestEngineRunnerTests.cs:line 111

13) Failed : NUnit.Engine.Runners.Tests.TestEngineRunnerTests<MultipleTestDomainRunner>(1).Load
  Expected: 31
  But was:  0
at NUnit.Engine.Runners.Tests.TestEngineRunnerTests`1.CheckBasicResult(XmlNode node) in C:\Repos\nunit-console\src\NUnitEngine\nunit.engine.tests\Runners\TestEngineRunnerTests.cs:line 157
at NUnit.Engine.Runners.Tests.TestEngineRunnerTests`1.CheckBasicResult(TestEngineResult result) in C:\Repos\nunit-console\src\NUnitEngine\nunit.engine.tests\Runners\TestEngineRunnerTests.cs:li
at NUnit.Engine.Runners.Tests.TestEngineRunnerTests`1.Load() in C:\Repos\nunit-console\src\NUnitEngine\nunit.engine.tests\Runners\TestEngineRunnerTests.cs:line 96

14) Failed : NUnit.Engine.Runners.Tests.TestEngineRunnerTests<MultipleTestDomainRunner>(1).Run
  Expected: 31
  But was:  0
at NUnit.Engine.Runners.Tests.TestEngineRunnerTests`1.CheckBasicResult(XmlNode node) in C:\Repos\nunit-console\src\NUnitEngine\nunit.engine.tests\Runners\TestEngineRunnerTests.cs:line 157
at NUnit.Engine.Runners.Tests.TestEngineRunnerTests`1.CheckRunResult(XmlNode result) in C:\Repos\nunit-console\src\NUnitEngine\nunit.engine.tests\Runners\TestEngineRunnerTests.cs:line 169
at NUnit.Engine.Runners.Tests.TestEngineRunnerTests`1.CheckRunResult(TestEngineResult result) in C:\Repos\nunit-console\src\NUnitEngine\nunit.engine.tests\Runners\TestEngineRunnerTests.cs:line
at NUnit.Engine.Runners.Tests.TestEngineRunnerTests`1.Run() in C:\Repos\nunit-console\src\NUnitEngine\nunit.engine.tests\Runners\TestEngineRunnerTests.cs:line 119

15) Failed : NUnit.Engine.Runners.Tests.TestEngineRunnerTests<MultipleTestDomainRunner>(1).RunAsync
  Expected: 31
  But was:  0
at NUnit.Engine.Runners.Tests.TestEngineRunnerTests`1.CheckBasicResult(XmlNode node) in C:\Repos\nunit-console\src\NUnitEngine\nunit.engine.tests\Runners\TestEngineRunnerTests.cs:line 157
at NUnit.Engine.Runners.Tests.TestEngineRunnerTests`1.CheckRunResult(XmlNode result) in C:\Repos\nunit-console\src\NUnitEngine\nunit.engine.tests\Runners\TestEngineRunnerTests.cs:line 169
at NUnit.Engine.Runners.Tests.TestEngineRunnerTests`1.CheckRunResult(TestEngineResult result) in C:\Repos\nunit-console\src\NUnitEngine\nunit.engine.tests\Runners\TestEngineRunnerTests.cs:line
at NUnit.Engine.Runners.Tests.TestEngineRunnerTests`1.RunAsync() in C:\Repos\nunit-console\src\NUnitEngine\nunit.engine.tests\Runners\TestEngineRunnerTests.cs:line 133

16) Failed : NUnit.Engine.Runners.Tests.TestEngineRunnerTests<MultipleTestDomainRunner>(3).CountTestCases
  Expected: 93
  But was:  0
at NUnit.Engine.Runners.Tests.TestEngineRunnerTests`1.CountTestCases() in C:\Repos\nunit-console\src\NUnitEngine\nunit.engine.tests\Runners\TestEngineRunnerTests.cs:line 103

17) Failed : NUnit.Engine.Runners.Tests.TestEngineRunnerTests<MultipleTestDomainRunner>(3).Explore
  Expected: 31
  But was:  0
at NUnit.Engine.Runners.Tests.TestEngineRunnerTests`1.CheckBasicResult(XmlNode node) in C:\Repos\nunit-console\src\NUnitEngine\nunit.engine.tests\Runners\TestEngineRunnerTests.cs:line 157
at NUnit.Engine.Runners.Tests.TestEngineRunnerTests`1.CheckBasicResult(TestEngineResult result) in C:\Repos\nunit-console\src\NUnitEngine\nunit.engine.tests\Runners\TestEngineRunnerTests.cs:li
at NUnit.Engine.Runners.Tests.TestEngineRunnerTests`1.Explore() in C:\Repos\nunit-console\src\NUnitEngine\nunit.engine.tests\Runners\TestEngineRunnerTests.cs:line 111

18) Failed : NUnit.Engine.Runners.Tests.TestEngineRunnerTests<MultipleTestDomainRunner>(3).Load
  Expected: 31
  But was:  0
at NUnit.Engine.Runners.Tests.TestEngineRunnerTests`1.CheckBasicResult(XmlNode node) in C:\Repos\nunit-console\src\NUnitEngine\nunit.engine.tests\Runners\TestEngineRunnerTests.cs:line 157
at NUnit.Engine.Runners.Tests.TestEngineRunnerTests`1.CheckBasicResult(TestEngineResult result) in C:\Repos\nunit-console\src\NUnitEngine\nunit.engine.tests\Runners\TestEngineRunnerTests.cs:li
at NUnit.Engine.Runners.Tests.TestEngineRunnerTests`1.Load() in C:\Repos\nunit-console\src\NUnitEngine\nunit.engine.tests\Runners\TestEngineRunnerTests.cs:line 96

19) Failed : NUnit.Engine.Runners.Tests.TestEngineRunnerTests<MultipleTestDomainRunner>(3).Run
  Expected: 31
  But was:  0
at NUnit.Engine.Runners.Tests.TestEngineRunnerTests`1.CheckBasicResult(XmlNode node) in C:\Repos\nunit-console\src\NUnitEngine\nunit.engine.tests\Runners\TestEngineRunnerTests.cs:line 157
at NUnit.Engine.Runners.Tests.TestEngineRunnerTests`1.CheckRunResult(XmlNode result) in C:\Repos\nunit-console\src\NUnitEngine\nunit.engine.tests\Runners\TestEngineRunnerTests.cs:line 169
at NUnit.Engine.Runners.Tests.TestEngineRunnerTests`1.CheckRunResult(TestEngineResult result) in C:\Repos\nunit-console\src\NUnitEngine\nunit.engine.tests\Runners\TestEngineRunnerTests.cs:line
at NUnit.Engine.Runners.Tests.TestEngineRunnerTests`1.Run() in C:\Repos\nunit-console\src\NUnitEngine\nunit.engine.tests\Runners\TestEngineRunnerTests.cs:line 119

20) Failed : NUnit.Engine.Runners.Tests.TestEngineRunnerTests<MultipleTestDomainRunner>(3).RunAsync
  Expected: 31
  But was:  0
at NUnit.Engine.Runners.Tests.TestEngineRunnerTests`1.CheckBasicResult(XmlNode node) in C:\Repos\nunit-console\src\NUnitEngine\nunit.engine.tests\Runners\TestEngineRunnerTests.cs:line 157
at NUnit.Engine.Runners.Tests.TestEngineRunnerTests`1.CheckRunResult(XmlNode result) in C:\Repos\nunit-console\src\NUnitEngine\nunit.engine.tests\Runners\TestEngineRunnerTests.cs:line 169
at NUnit.Engine.Runners.Tests.TestEngineRunnerTests`1.CheckRunResult(TestEngineResult result) in C:\Repos\nunit-console\src\NUnitEngine\nunit.engine.tests\Runners\TestEngineRunnerTests.cs:line
at NUnit.Engine.Runners.Tests.TestEngineRunnerTests`1.RunAsync() in C:\Repos\nunit-console\src\NUnitEngine\nunit.engine.tests\Runners\TestEngineRunnerTests.cs:line 133

21) Failed : NUnit.Engine.Runners.Tests.TestEngineRunnerTests<TestDomainRunner>.CountTestCases
  Expected: 31
  But was:  0
at NUnit.Engine.Runners.Tests.TestEngineRunnerTests`1.CountTestCases() in C:\Repos\nunit-console\src\NUnitEngine\nunit.engine.tests\Runners\TestEngineRunnerTests.cs:line 103

22) Failed : NUnit.Engine.Runners.Tests.TestEngineRunnerTests<TestDomainRunner>.Explore
  Expected: 31
  But was:  0
at NUnit.Engine.Runners.Tests.TestEngineRunnerTests`1.CheckBasicResult(XmlNode node) in C:\Repos\nunit-console\src\NUnitEngine\nunit.engine.tests\Runners\TestEngineRunnerTests.cs:line 157
at NUnit.Engine.Runners.Tests.TestEngineRunnerTests`1.CheckBasicResult(TestEngineResult result) in C:\Repos\nunit-console\src\NUnitEngine\nunit.engine.tests\Runners\TestEngineRunnerTests.cs:li
at NUnit.Engine.Runners.Tests.TestEngineRunnerTests`1.Explore() in C:\Repos\nunit-console\src\NUnitEngine\nunit.engine.tests\Runners\TestEngineRunnerTests.cs:line 111

23) Failed : NUnit.Engine.Runners.Tests.TestEngineRunnerTests<TestDomainRunner>.Load
  Expected: 31
  But was:  0
at NUnit.Engine.Runners.Tests.TestEngineRunnerTests`1.CheckBasicResult(XmlNode node) in C:\Repos\nunit-console\src\NUnitEngine\nunit.engine.tests\Runners\TestEngineRunnerTests.cs:line 157
at NUnit.Engine.Runners.Tests.TestEngineRunnerTests`1.CheckBasicResult(TestEngineResult result) in C:\Repos\nunit-console\src\NUnitEngine\nunit.engine.tests\Runners\TestEngineRunnerTests.cs:li
at NUnit.Engine.Runners.Tests.TestEngineRunnerTests`1.Load() in C:\Repos\nunit-console\src\NUnitEngine\nunit.engine.tests\Runners\TestEngineRunnerTests.cs:line 96

24) Failed : NUnit.Engine.Runners.Tests.TestEngineRunnerTests<TestDomainRunner>.Run
  Expected: 31
  But was:  0
at NUnit.Engine.Runners.Tests.TestEngineRunnerTests`1.CheckBasicResult(XmlNode node) in C:\Repos\nunit-console\src\NUnitEngine\nunit.engine.tests\Runners\TestEngineRunnerTests.cs:line 157
at NUnit.Engine.Runners.Tests.TestEngineRunnerTests`1.CheckRunResult(XmlNode result) in C:\Repos\nunit-console\src\NUnitEngine\nunit.engine.tests\Runners\TestEngineRunnerTests.cs:line 169
at NUnit.Engine.Runners.Tests.TestEngineRunnerTests`1.CheckRunResult(TestEngineResult result) in C:\Repos\nunit-console\src\NUnitEngine\nunit.engine.tests\Runners\TestEngineRunnerTests.cs:line
at NUnit.Engine.Runners.Tests.TestEngineRunnerTests`1.Run() in C:\Repos\nunit-console\src\NUnitEngine\nunit.engine.tests\Runners\TestEngineRunnerTests.cs:line 119

25) Failed : NUnit.Engine.Runners.Tests.TestEngineRunnerTests<TestDomainRunner>.RunAsync
  Expected: 31
  But was:  0
at NUnit.Engine.Runners.Tests.TestEngineRunnerTests`1.CheckBasicResult(XmlNode node) in C:\Repos\nunit-console\src\NUnitEngine\nunit.engine.tests\Runners\TestEngineRunnerTests.cs:line 157
at NUnit.Engine.Runners.Tests.TestEngineRunnerTests`1.CheckRunResult(XmlNode result) in C:\Repos\nunit-console\src\NUnitEngine\nunit.engine.tests\Runners\TestEngineRunnerTests.cs:line 169
at NUnit.Engine.Runners.Tests.TestEngineRunnerTests`1.CheckRunResult(TestEngineResult result) in C:\Repos\nunit-console\src\NUnitEngine\nunit.engine.tests\Runners\TestEngineRunnerTests.cs:line
at NUnit.Engine.Runners.Tests.TestEngineRunnerTests`1.RunAsync() in C:\Repos\nunit-console\src\NUnitEngine\nunit.engine.tests\Runners\TestEngineRunnerTests.cs:line 133

Run Settings
    BasePath: C:\Repos\nunit-console\src\NUnitEngine\nunit.engine.tests\..\..\..\bin\Debug\
    DisposeRunners: True
    WorkDirectory: C:\Repos\core-net-api\packages\NUnit.ConsoleRunner.3.7.0\tools
    ImageRuntimeVersion: 2.0.50727
    ImageRequiresX86: False
    ImageRequiresDefaultAppDomainAssemblyResolver: False
    NumberOfTestWorkers: 4

Test Run Summary
  Overall result: Failed
  Test Count: 500, Passed: 469, Failed: 25, Warnings: 0, Inconclusive: 5, Skipped: 1
    Failed Tests - Failures: 25, Errors: 0, Invalid: 0
    Skipped Tests - Ignored: 0, Explicit: 1, Other: 0
  Start time: 2017-08-07 08:07:59Z
    End time: 2017-08-07 08:08:11Z
    Duration: 11.898 seconds

Results (nunit3) saved as TestResult.xml
PS C:\Repos\core-net-api\packages\NUnit.ConsoleRunner.3.7.0\tools>
```
Any ideas ? :)

**Comment by CharliePoole** [comment]
You encountered a bug that is hiding a bigger bug!

The VS Project Loader extension for the NUnit Engine does not support the format of .NET Core projects. A PR to fix this is in review right now: nunit/vs-project-loader#12

However, once this is merged and in use, you would run into the more fundamental error, which is that the engine itself does not support .NET Core assemblies. :-( That too is being worked on.

**Comment by przemo098** [comment]
Okey, but does it mean .Net standard is also not supported ?!
At main page you wrote:

![image](https://user-images.githubusercontent.com/6282239/29020745-5990c9ca-7b63-11e7-833a-ab220a1262e4.png)

By .Net Standard we mean new .csproj format (this introduced by Microsoft after resigning from json).

**Comment by CharliePoole** [comment]
I agree it's confusing. As indicated, there is now a ".NET Standard version of the engine". It's not the full engine used by the console runner and is only designed for use by the vs adapter and similar programs.

The console runner __will__ support various implementations of .NET Standard, including .NET Core but right now it only runs tests for .NET (desktop) 2.0 and higher. 

Supporting the .csproj format merely allows us to find out the name of the dll that is to be run. It's a small step but an important one.

**Comment by przemo098** [comment]
Okey but I'm targeting output to net461.
In this case I can run console tests, Resharper tests.
But Visual Studio test explorer shows still nothing...

**Comment by CharliePoole** [comment]
Misunderstanding then. You posted this as a console issue, so I wasn't thinking about the adapter.

Which NUnit framework build are you referencing? Which runtime target? (Should be .NET 4.5)

**Comment by ChrisMaddock** [comment]
Closing as this needs more information to be able to solve.

Happy to reopen if we can help.
