### ISSUE TITLE
Invalid --framework option throws exception

### ISSUE THREAD

**Issue by ChrisMaddock** [nunit/nunit-console#298]
I can never remember the framework names, so I guessed at:

    nunit3-console .\Tests.exe --framework=20

This throws the following stack trace:

```
System.ArgumentException: Version string portion was too short or too long.
   at System.Version.VersionResult.SetFailure(ParseFailureKind failure, String argument)
   at System.Version.TryParseVersion(String version, VersionResult& result)
   at System.Version.Parse(String input)
   at System.Version..ctor(String version)
   at NUnit.Engine.RuntimeFramework.Parse(String s)
   at NUnit.Engine.Services.RuntimeFrameworkService.IsAvailable(String name)
   at NUnit.Engine.Runners.MasterTestRunner.ValidatePackageSettings()
   at NUnit.Engine.Runners.MasterTestRunner.InitializePackage()
   at NUnit.Engine.TestEngine.GetRunner(TestPackage package)
   at NUnit.ConsoleRunner.ConsoleRunner.RunTests(TestPackage package, TestFilter filter)
   at NUnit.ConsoleRunner.Program.Main(String[] args)
```

We shouldn't throw an exception in this case, and instead return an invalid argument notice.

**Comment by CharliePoole** [comment]
The choice is between fixing `RuntimeFramework` and fixing `MasterTestRunner`. But the `RuntimeFramework.Parse` method is called in four different places in the engine, so it makes sense to do the fix there. My inclination would be to make it into a `TryParse` method.
