### ISSUE TITLE
Attempting to target too low a framework throws exception

### ISSUE THREAD

**Issue by ChrisMaddock** [nunit/nunit-console#299]
I just tried to run my tests built against .NET 4.0 with `--framework=2.0`. This threw the following exception:
```
1) Error :
An exception occurred in the driver while loading tests.

Server stack trace:
   at NUnit.Engine.Runners.DirectTestRunner.LoadDriver(IFrameworkDriver driver, String testFile, TestPackage subPackage)
   at NUnit.Engine.Runners.DirectTestRunner.LoadPackage()
   at NUnit.Engine.Runners.DirectTestRunner.EnsurePackageIsLoaded()
   at NUnit.Engine.Runners.DirectTestRunner.RunTests(ITestEventListener listener, TestFilter filter)
   at NUnit.Engine.Agents.RemoteTestAgent.Run(ITestEventListener listener, TestFilter filter)
   at System.Runtime.Remoting.Messaging.StackBuilderSink._PrivateProcessMessage(IntPtr md, Object[] args, Object server, Int32 methodPtr, Boolean fExecuteInContext, Object[]& outArgs)
   at System.Runtime.Remoting.Messaging.StackBuilderSink.SyncProcessMessage(IMessage msg, Int32 methodPtr, Boolean fExecuteInContext)

Exception rethrown at [0]:
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at NUnit.Engine.ITestEngineRunner.Run(ITestEventListener listener, TestFilter filter)
   at NUnit.Engine.Runners.ProcessRunner.RunTests(ITestEventListener listener, TestFilter filter)
```

I think we used to have specific handling for this situation which returned a helpful error message. We should check for that - and add some if not.

**Comment by CharliePoole** [comment]
I think it used to work as well. Somebody may need to figure out what happened and leave some info for the person who works it if we are making this "help wanted." 

BTW, can we clarify the definition of labels in the wiki to include this and say what it means. In particular, it sounds a bit different from the old up for grabs label. That is, "help wanted" would sound to me like "we don't intend/know how to fix this unless somebody else volunteers" but I don't think that's our intent.
