### ISSUE TITLE
Tests with ExpectedResult = x failing on TeamCity

### ISSUE THREAD

**Issue by kaylanimis** [nunit/nunit-console#338]
Hello,

I'm running nunit 3.9.0 and the console 3.7.0 on a teamcity build server v. 2017.1.5. For test cases that use the ExpectedResult attribute, we're seeing test breaks when run on the build server, but not when run in Visual Studio. 

Example:
`[TestCase(Int32.MinValue + 101, Int32.MinValue + 100, ExpectedResult = 1)]
        public int RoundUpDivision(int dividend, int divisor)
        {
            return MathEx.RoundUpDivision(dividend, divisor);
        }`

Result:
`Test(s) failed.   Expected: null
  But was:  1

   at NUnit.Framework.Assert.ReportFailure(String message)
   at NUnit.Framework.Assert.That[TActual](TActual actual, IResolveConstraint expression, String message, Object[] args)
   at NUnit.Framework.Assert.AreEqual(Object expected, Object actual)`

We also see this with bool expected results:
`======= Failed test run #1 ==========
Test(s) failed.   Expected: null
  But was:  False

   at NUnit.Framework.Assert.ReportFailure(String message)
   at NUnit.Framework.Assert.That[TActual](TActual actual, IResolveConstraint expression, String message, Object[] args)
   at NUnit.Framework.Assert.AreEqual(Object expected, Object actual)
======= Failed test run #2 ==========
Test(s) failed.   Expected: null
  But was:  False

   at NUnit.Framework.Assert.ReportFailure(String message)
   at NUnit.Framework.Assert.That[TActual](TActual actual, IResolveConstraint expression, String message, Object[] args)
   at NUnit.Framework.Assert.AreEqual(Object expected, Object actual)`

Is there a compatibility issue here that I've missed?

Thanks,
Kayla

**Comment by kaylanimis** [comment]
This was user error when setting up the team city build, apologies for the confusion.
