### ISSUE TITLE
Rare registry configurations may cause NUnit to fail

### ISSUE THREAD

**Issue by SteveGilham** [nunit/nunit-console#46]
Having recently upgraded my NUnit version on one of my old machines I got

```
NUnit-Console version 2.6.4.14350
Copyright (C) 2002-2012 Charlie Poole.
Copyright (C) 2002-2004 James W. Newkirk, Michael C. Two, Alexei A. Vorontsov.
Copyright (C) 2000-2002 Philip Craig.
All Rights Reserved.

Runtime Environment -
   OS Version: Microsoft Windows NT 6.0.6002 Service Pack 2
  CLR Version: 2.0.50727.4253 ( Net 3.5 )

ProcessModel: Default    DomainUsage: Single
Execution Runtime: net-3.5
Unhandled Exception:
System.ArgumentException: Version string portion was too short or too long.
   at System.Version..ctor(String version)
   at NUnit.Core.RuntimeFramework.AppendDotNetFrameworks(FrameworkCollection frameworks)
   at NUnit.Core.RuntimeFramework.get_AvailableFrameworks()
   at NUnit.Core.RuntimeFramework.get_IsAvailable()
   at NUnit.Util.RuntimeFrameworkSelector.SelectRuntimeFramework(TestPackage package)
   at NUnit.Util.DefaultTestRunnerFactory.GetTargetProcessModel(TestPackage package)
   at NUnit.Util.DefaultTestRunnerFactory.MakeTestRunner(TestPackage package)
   at NUnit.ConsoleRunner.ConsoleUi.Execute(ConsoleOptions options)
   at NUnit.ConsoleRunner.Runner.Main(String[] args)
```

Looking through the code and then at the registry, I found that I still had the .net 4 Beta 2 Windows Update Opt-in Key `HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4B2WU` (see http://www.hanselman.com/blog/FavorHelpUsTestNET4Beta2OnWindowsUpdateWU.aspx).

While this particular case may affect about one other person who forgot to delete this key, it suggests that there may in future be other legitimate instances where keys beginning v may not be followed by a version number; and such keys should be skipped (possibly with a warning logged).

**Comment by CharliePoole** [comment]
As it says at https://github.com/nunit/nunit-console, "OLD repo for 3.0 console - no longer used - file issues under nunit/nunit." I made a new issue there and copied in your description. You will probably have to subscribe to the issue if you want to see updates. It's issue #454.
