### ISSUE TITLE
ArgumentException: DTD is prohibited in this XML document

### ISSUE THREAD

**Issue by mikkelbu** [nunit/nunit-console#473]
@mnkjadhav commented on [Thu Aug 10 2017](https://github.com/nunit/nunit-transforms/issues/10)

[TestResult.zip](https://github.com/nunit/nunit-transforms/files/1214306/TestResult.zip)

When run NUnit tests using nunit3-console.exe with transform option, I get below error

NUnit.Engine.NUnitEngineException: The path specified in --result junit-results. xml could not be written to ---> System.ArgumentException: Unable to load transform nunit3-junit.xslt ---> System.Xml.XmlException: For security reasons DTD is prohibited in this XML document. To enable DTD processing set the DtdProcessing property on XmlReaderSettings to Parse and pass the settings into XmlReader.Create method.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.ParseDoctypeDecl()
   at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   at System.Xml.Xsl.Xslt.XsltInput.ReadTextNodes()
   at System.Xml.Xsl.Xslt.XsltInput.ReadNextSibling()
   at System.Xml.Xsl.Xslt.XsltInput.FindStylesheetElement()
   at System.Xml.Xsl.Xslt.XsltLoader.LoadDocument()
   at System.Xml.Xsl.Xslt.XsltLoader.LoadStylesheet(XmlReader reader, Boolean include)
   --- End of inner exception stack trace ---
   at NUnit.Engine.Services.XmlTransformResultWriter..ctor(Object[] args)
   at NUnit.Engine.Services.ResultService.GetResultWriter(String format, Object[] args)
   at NUnit.ConsoleRunner.ConsoleRunner.RunTests(TestPackage package, TestFilter filter)
   --- End of inner exception stack trace ---
   at NUnit.ConsoleRunner.ConsoleRunner.RunTests(TestPackage package, TestFilter filter)
   at NUnit.ConsoleRunner.Program.Main(String[] args)

---

@hadanang commented on [Tue Aug 28 2018](https://github.com/nunit/nunit-transforms/issues/10#issuecomment-416464873)

I also got this error:
NUnit.Engine.NUnitEngineException : Error encountered in resolving output specification: OutputPath: report.xml, Format: user, Transform: C:\NUnit.Console-3.8.0\nunit3-junit.xslt
  ----> System.ArgumentException : Unable to load transform C:\NUnit.Console-3.8.0\nunit3-junit.xslt
  ----> System.Xml.XmlException : For security reasons DTD is prohibited in this XML document. To enable DTD processing set the DtdProcessing property on XmlReaderSettings to Parse and pass the settings into XmlReader.Create method.

--NUnitEngineException
   at NUnit.ConsoleRunner.ConsoleRunner.RunTests(TestPackage package, TestFilter filter)
   at NUnit.ConsoleRunner.Program.Main(String[] args)
--ArgumentException
   at NUnit.Engine.Services.XmlTransformResultWriter..ctor(Object[] args)
   at NUnit.Engine.Services.ResultService.GetResultWriter(String format, Object[] args)
   at NUnit.ConsoleRunner.ConsoleRunner.RunTests(TestPackage package, TestFilter filter)
--XmlException
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.ParseDoctypeDecl()
   at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   at System.Xml.Xsl.Xslt.XsltInput.ReadTextNodes()
   at System.Xml.Xsl.Xslt.XsltInput.ReadNextSibling()
   at System.Xml.Xsl.Xslt.XsltInput.FindStylesheetElement()
   at System.Xml.Xsl.Xslt.XsltLoader.LoadDocument()
   at System.Xml.Xsl.Xslt.XsltLoader.LoadStylesheet(XmlReader reader, Boolean include)

---

@jnm2 commented on [Fri Aug 31 2018](https://github.com/nunit/nunit-transforms/issues/10#issuecomment-417715620)

@nunit/engine-team This looks like a console bug. Should we move it?

---

@ChrisMaddock commented on [Fri Aug 31 2018](https://github.com/nunit/nunit-transforms/issues/10#issuecomment-417786785)

I agree - but don’t (yet) know enough the security implications to know what to do here.

Sorry - on my phone, or I’d move it now!

---

@jnm2 commented on [Mon Sep 24 2018](https://github.com/nunit/nunit-transforms/issues/10#issuecomment-424128230)

@nunit/engine-team Does anyone have a tool that can move this issue?

**Comment by jnm2** [comment]
Can we use `DtdProcessing.Ignore`?

**Comment by mikkelbu** [comment]
Having read a little about `DtdProcessing` yesterday I'm fine with `DtdProcessing.Ignore`. I could also live with `DtdProcessing.Parse` as the users themself specify the transformation file.

Ps. The strange part is that `nunit3-junit.xslt` does not contain a DTD. The only way I could get a document with a DTD was to try to attempt to download the file like below, but that just downloads the homepage (and that contains a DTD). Sorry about the size, but GH tries to fill the entire width AFAICT.
![image](https://user-images.githubusercontent.com/1007631/48959288-a6435a00-ef64-11e8-999b-8705ec37a657.png)

**Comment by jnm2** [comment]
> Sorry about the size, but GH tries to fill the entire width AFAICT.

This has irritated me on many occasions. It actually doesn't fill the entire width. What happens is that you're at something like 200% DPI and either no DPI info is encoded into the PNG or else the browser does not respect it.

**Comment by ChrisMaddock** [comment]
> Having read a little about DtdProcessing yesterday I'm fine with DtdProcessing.Ignore. I could also live with DtdProcessing.Parse as the users themself specify the transformation file.

@mikkelbu I know nothing about the specifics here, but trust your judgement. Want to PR this, and get this issue finished off? 😄
