### ISSUE TITLE
DefaultSuiteBuilder fails to resolve assembly references

### ISSUE THREAD

**Issue by y-skindersky** [nunit/nunit-console#500]
I have used nunit to run functional tests for my own API' libraries. In my case these API libraries and test libraries are located in different folders. I have added SetUpFixture with OneTimeSetUp method which subscribes to AppDomain.CurrentDomain.AssemblyResolve and provides necessary dependencies (it uses environment variable to get path to the installed API libraries). It works fine for the most cases but I have problems with passing API types as test parameters. In this case nunit fails to load necessary API assembly:

System.IO.FileNotFoundException: Could not load file or assembly 'API.Classes, Version=x.x.x.x, Culture=neutral, PublicKeyToken=xxxxxxxxxxxxxxxx' or one of its dependencies. The system cannot find the file specified.
File name: 'API.Classes, Version=x.x.x.x, Culture=neutral, PublicKeyToken=xxxxxxxxxxxxxxxx'
   at System.Signature.GetSignature(Void* pCorSig, Int32 cCorSig, RuntimeFieldHandleInternal fieldHandle, IRuntimeMethodInfo methodHandle, RuntimeType declaringType)
   at System.Reflection.RuntimeMethodInfo.FetchNonReturnParameters()
   at System.Reflection.RuntimeMethodInfo.GetParameters()
   at NUnit.Framework.Internal.MethodWrapper.GetParameters()
   at NUnit.Framework.CombiningStrategyAttribute.BuildFrom(IMethodInfo method, Test suite)
   at NUnit.Framework.Internal.Builders.DefaultTestCaseBuilder.BuildFrom(IMethodInfo method, Test parentSuite)
   at NUnit.Framework.Internal.Builders.NUnitTestFixtureBuilder.AddTestCasesToFixture(TestFixture fixture)
   at NUnit.Framework.Internal.Builders.NUnitTestFixtureBuilder.BuildFrom(ITypeInfo typeInfo, ITestFixtureData testFixtureData)
   at NUnit.Framework.TestFixtureAttribute.<BuildFrom>d__48.MoveNext()
   at NUnit.Framework.Internal.Builders.DefaultSuiteBuilder.BuildFrom(ITypeInfo typeInfo)

Are there any way to provide nunit appdomain with own assembly resolving handler?

**Comment by y-skindersky** [comment]
Code snippet of failing test:

        [Test]
        [Combinatorial]
        public void TestTraceControlLocalization(
            [Values(TraceCategory.Project, TraceCategory.Application, TraceCategory.Master, TraceCategory.Slave)] 
            TraceCategory traceCategory,

            [Values(Dictionary.SupportedLocaleIds.English_1033, Dictionary.SupportedLocaleIds.German_1031)] 
            Dictionary.SupportedLocaleIds supportedLocale)
        {

        }

**Comment by ChrisMaddock** [comment]
I guess this is because your Values attributes are being evaluated to build the test assembly before the SetUpFixture is being run.

As an ugly fix, and mainly out of curiosity, would it work if you refactored your Values attributes to use ValuesSouceAttribute, and then do the resolver setup at the start of the ValuesSourceAttribute, which should be encountered before the tests are then created?

A slightly 'nicer' fix, although perhaps still slightly against expected usage might be to implement an IDriverFactory and driver, which will allow you to get hold of the appdomain before anything is ran in it, and then making the necessary changes there. It should be possible to replicate the NUnit3DriverFactory, just with the extra change. Docs for that here: https://github.com/nunit/docs/wiki/Framework-Drivers

Let us know how it goes! 👍

**Comment by ChrisMaddock** [comment]
Closing this, as I think the questions answered. Feel free to comment further if not, the team will still get the notifications. 🙂
