### ISSUE TITLE
Create result directory if it does not exist

### ISSUE THREAD

**Issue by jnm2** [nunit/nunit-console#501]
Right now if the directory does not already exist for the result file path, you get this:

```
NUnit.Engine.NUnitEngineException : The path specified in --result C:/Users/Joseph/Source/Repos/nunit/test-results/net20/nunit.framework.tests.xml could not be written to
  ----> System.IO.DirectoryNotFoundException : Could not find a part of the path 'C:\Users\Joseph\Source\Repos\nunit\test-results\net20\nunit.framework.tests.xml'.

--NUnitEngineException
The path specified in --result C:/Users/Joseph/Source/Repos/nunit/test-results/net20/nunit.framework.tests.xml could not be written to
   at NUnit.ConsoleRunner.ConsoleRunner.RunTests(TestPackage package, TestFilter filter)
   at NUnit.ConsoleRunner.Program.Main(String[] args)
--
DirectoryNotFoundException
Could not find a part of the path 'C:\Users\Joseph\Source\Repos\nunit\test-results\net20\nunit.framework.tests.xml'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access)
   at NUnit.Engine.Services.NUnit3XmlResultWriter.WriteResultFile(XmlNode resultNode, String outputPath)
   at NUnit.ConsoleRunner.ConsoleRunner.RunTests(TestPackage package, TestFilter filter)
```

It would be convenient if the directory was just created.

**Comment by JerryBLi** [comment]
Hey, I just submitted a Pull request #539 for this. Do you think this warrants a test to be written?

**Comment by jnm2** [comment]
Could follow up by removing https://github.com/nunit/nunit/blob/4584f8f5540bba7ee5abb7af3eea7c2b500e002b/build.cake#L415 when 3.10 is released.
