### ISSUE TITLE
Trailing \ in --work argument causes agent to crash

### ISSUE THREAD

**Issue by appel1** [nunit/nunit-console#605]
After upgrading to NUnit.ConsoleRunner 3.10 the --work argument no longer works with a trailing \\. 

```
c:\source>packages\NUnit.ConsoleRunner.3.10.0\tools\nunit3-console.exe bin\debug\tests.dll --work=c:\source\build\reports\

NUnit Console Runner 3.10.0 (.NET 2.0)
Copyright (c) 2019 Charlie Poole, Rob Prouse
den 8 april 2019 11:27:05

Runtime Environment
   OS Version: Microsoft Windows NT 10.0.17134.0
  CLR Version: 4.0.30319.42000

Test Files
    C:\source\bin\debug\tests.dll


Unhandled Exception: NUnit.Engine.NUnitEngineException: Remote test agent exited with non-zero exit code -532462766
   at NUnit.Engine.Services.TestAgency.OnAgentExit(Object sender, EventArgs e)
   at System.Diagnostics.Process.OnExited()
   at System.Diagnostics.Process.RaiseOnExited()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading._ThreadPoolWaitOrTimerCallback.PerformWaitOrTimerCallback(Object state, Boolean timedOut)

Errors, Failures and Warnings

1) Error :
NUnit.Engine.NUnitEngineException : Unable to acquire remote process agent
--NUnitEngineException
Unable to acquire remote process agent
   at NUnit.Engine.Runners.ProcessRunner.CreateAgentAndRunner()
   at NUnit.Engine.Runners.ProcessRunner.RunTests(ITestEventListener listener, TestFilter filter)

Test Run Summary
  Overall result: Failed
  Test Count: 0, Passed: 0, Failed: 0, Warnings: 0, Inconclusive: 0, Skipped: 0
  Start time: 2019-04-08 09:27:05Z
    End time: 2019-04-08 09:27:07Z
    Duration: 1.631 seconds

Results (nunit3) saved as TestResult.xml
```

**Comment by mikkelbu** [comment]
This is an unfortunate side-effect of the change done in #585. When we escape the path with quotes then we end up setting the arguments of the agents to something like this (abbreviated for readability)
```csharp
"0c8b...cc0 tcp://127.0.0.1:58129/TestAgency --pid=356 --work=\"C:\\Temp\\Trace Output\\\""
```
The effect is that the fourth argument to the agent becomes `--work=C:\Temp\Trace Output"` (notice the " in the end of the string).

If the path did not end with a trailing `\` we would send 
```csharp
"0c8b...cc0 tcp://127.0.0.1:58129/TestAgency --pid=356 --work=\"C:\\Temp\\Trace Output\""
```
which would make the fourth argument become `--work=C:\Temp\Trace Output`.

**Comment by ChrisMaddock** [comment]
This area needs some unit tests. 🙁 

@appel1 - Pushing a fix now. Just to sense check, the workaround is just to drop the slash right, doing that doesn't break your set up in another way?

It's annoying that this broke, but I think it can wait until the next major release, unless I'm missing something.

**Comment by appel1** [comment]
@ChrisMaddock Sounds good to me. 

I worked around the issue by trimming the path in our build script.
