### ISSUE TITLE
Exception NUnit.Engine.NUnitEngineUnloadException

### ISSUE THREAD

**Issue by mkmita** [nunit/nunit-console#708]
Hello,

I run command

dotnet test ./Tests.Integration.csproj --configuration $configuration --no-build --framework net472 --logger 'trx;logfilename="test-results.trx"'

And i get warning about exception in the end.

Exception NUnit.Engine.NUnitEngineUnloadException,    Exception thrown unloading tests from C:\\documents\code\Tests.Integration\bin\Debug\net472\Tests.Integration.dll
Exception encountered unloading application domain
   at NUnit.Engine.Services.DomainManager.DomainUnloader.Unload()
   at NUnit.Engine.Runners.TestDomainRunner.UnloadPackage()
   at NUnit.Engine.Runners.AbstractTestRunner.Dispose(Boolean disposing)
   at NUnit.Engine.Runners.AbstractTestRunner.Dispose()
   at NUnit.Engine.Runners.MasterTestRunner.Dispose(Boolean disposing)
   at NUnit.Engine.Runners.MasterTestRunner.Dispose()
   at NUnit.VisualStudio.TestAdapter.NUnit3TestExecutor.RunAssembly(String assemblyPath, IGrouping`2 testCases, TestFilter filter) in D:\repos\NUnit\nunit3-vs-adapter\src\NUnitTestAdapter\NUnit3TestExecutor.cs:line 330
Innerexception: NUnit.Engine.NUnitEngineException: Exception encountered unloading application domain: Error while unloading appdomain. (Exception from HRESULT: 0x80131015)
Application domain name: domain-3736d855-Tests.Integration.dll
Application domain BaseDirectory: C:\documents\code\Tests.Integration\bin\Debug\net472\

Nunit 3.12.0
Nunit3testadapter 3.15.1

Maybe somebody could point me to common mistakes which leads to this error?

**Comment by ChrisMaddock** [comment]
Not sure, sorry. I thought that error was supressed in the 3.15.1 adapter to be honest. @OsirisTerje, any ideas?

**Comment by mkmita** [comment]
@ChrisMaddock no problem. Thank you for taking your time answering me. Problem was I did not close connection to rabit properly. Fixed it and error gone now.
