### ISSUE TITLE
FYI: 3.12.0-beta1 (NetCore) errors with SpecFlow

### ISSUE THREAD

**Issue by Q-Division** [nunit/nunit-console#815]
I have a hunch this is probably an "error" on the SpecFlow side (haven't quite worked it out yet) but as an FYI, I'll add the details here (hope that's OK). 

For ref. the setup works OK for the net48 build with the netfx runner.

--- 
nunit3-console.exe .\executables\Vision\integration\bin\x64\Release\netcoreapp3.1\Vision.IntegrationTests.dll

NUnit Console Runner 3.12.0-beta1
Copyright (c) 2020 Charlie Poole, Rob Prouse
04 September 2020 15:28:14

Runtime Environment
   OS Version: Microsoft Windows 10.0.19041
  Runtime: .NET Core 3.1.7

Test Files
    .\executables\Vision\integration\bin\x64\Release\netcoreapp3.1\Vision.IntegrationTests.dll

-> Loading plugin <...>\executables\Vision\integration\bin\x64\Release\netcoreapp3.1\TechTalk.SpecFlow.NUnit.SpecFlowPlugin.dll
-> Missing [assembly:RuntimePlugin] attribute in TechTalk.SpecFlow.NUnit.SpecFlowPlugin, Version=3.4.0.0, Culture=neutral, PublicKeyToken=0778194805d6db41. Please check https://go.specflow.org/doc-plugins for details.

Errors, Failures and Warnings

1) SetUp Error : Vision_IntegrationTests_NUnitAssemblyHooks
BoDi.ObjectContainerException : Interface cannot be resolved: TechTalk.SpecFlow.UnitTestProvider.IUnitTestRuntimeProvider('nunit')
   at BoDi.ObjectContainer.TypeRegistration.Resolve(ObjectContainer container, RegistrationKey keyToResolve, ResolutionList resolutionPath)
   at BoDi.ObjectContainer.ResolveObject(RegistrationKey keyToResolve, ResolutionList resolutionPath)
   at BoDi.ObjectContainer.Resolve(Type typeToResolve, ResolutionList resolutionPath, String name)
   at BoDi.ObjectContainer.Resolve(Type typeToResolve, String name)
   at BoDi.ObjectContainer.Resolve[T](String name)
   at TechTalk.SpecFlow.Infrastructure.ContainerBuilder.CreateGlobalContainer(Assembly testAssembly, IRuntimeConfigurationProvider configurationProvider)
   at TechTalk.SpecFlow.TestRunnerManager.CreateTestRunnerManager(Assembly testAssembly, IContainerBuilder containerBuilder)
   at TechTalk.SpecFlow.TestRunnerManager.GetTestRunnerManager(Assembly testAssembly, IContainerBuilder containerBuilder, Boolean createIfMissing)
   at TechTalk.SpecFlow.TestRunnerManager.OnTestRunStart(Assembly testAssembly, IContainerBuilder containerBuilder)
   at Vision_IntegrationTests_NUnitAssemblyHooks.AssemblyInitialize() in <...>\executables\Vision\integration\obj\x64\Release\netcoreapp3.1\NUnit.AssemblyHooks.cs:line 18

**Comment by Q-Division** [comment]
Rob, I did think the same and see if I can debug it any further but put it here just in case "you" knew something had changed. For ref. I didn't get the same error via the Resharper runner (but I don't know exactlty how that's running). If I can work out any more I'll post it here either for completeness (and close) or whatever the next step might be.

**Comment by rprouse** [comment]
A bit of googling shows many people with the same error with multiple test frameworks. For example, https://github.com/SpecFlowOSS/SpecFlow/issues/1803

One fix mentioned is that you must now add the `SpecFlow.NUnit` package to your project. This wasn't required before. There is also another workaround in https://github.com/SpecFlowOSS/SpecFlow/issues/1760.

I'm going to mark this as a question and close it. If you find more information @Q-Division please add it to this issue for others with the same problem.
